---
aliases:
- /coolnamehere/2005/03/07_04-repeating-yourself.html
- /post/2005/04-repeating-yourself/
- /2005/03/07/rebol-babysteps-04-repeating-yourself/
date: 2005-03-07 00:00:00+00:00
tags:
- rebol
- learn
- coolnamehere
title: REBOL Babysteps - 04 Repeating Yourself
updated: 2009-07-11 00:00:00+00:00
series:
- REBOL Babysteps
uuid: 6e55c669-8532-45ba-a3c8-24868eec3d54
format: adoc
---
<div class="paragraph">
<p>Now we know how to do things, and we know how to choose whether or not we will do something.
We’re getting close to having some real skills.
We just need to get the understanding of one more concept before we reach the first little plateau of programming knowledge.
We need to learn how to do a task more than once.
Well, besides just running the script again, but that doesn’t really count.</p>
</div>
<div class="sect1">
<h2 id="_simple_loops">Simple Loops</h2>
<div class="sectionbody">
<div class="paragraph">
<p>The simplest sort of repetition involves doing exactly the same thing again and again.
The simplest sort of repetition involves doing exactly the same thing again and again.
The simplest sort of repetition involves doing exactly the same thing again and again.
The simplest sort of repetition –</p>
</div>
<div class="paragraph">
<p>Sorry, I got carried away.
Hopefully you get the idea. Sometimes all you need to do is repeat a process a set number of times.</p>
</div>
<div class="sect2">
<h3 id="_loop"><code>loop</code></h3>
<div class="literalblock">
<div class="content">
<pre>&gt;&gt; loop 5 [
[    print "Spam!"
[    ]
Spam!
Spam!
Spam!
Spam!
Spam!</pre>
</div>
</div>
<div class="paragraph">
<p>That’s a little boring.
Let’s try something a little more involved.
Maybe we could use <code>loop</code> to create a simple math quiz program.</p>
</div>
<div class="listingblock">
<div class="content">
<pre class="pygments highlight"><code data-lang="rebol"><span></span><span class="tok-gs">REBOL [</span>
    <span class="tok-gu">Title:</span> <span class="tok-s">&quot;Simple Math Quiz&quot;</span>
    <span class="tok-gu">File:</span> <span class="tok-nd">%math.r</span>
<span class="tok-gs">]</span>

<span class="tok-c">; Seed the randomizer with the current time to get better random values</span>
<span class="tok-nf">random</span><span class="tok-na">/seed</span> <span class="tok-nb">now</span>

<span class="tok-gu">correct:</span> <span class="tok-m">0</span>
<span class="tok-gu">questions:</span> <span class="tok-m">5</span>

<span class="tok-nb">loop</span> <span class="tok-nv">questions</span> <span class="tok-gs">[</span>

    <span class="tok-c">; Create a simple multiplication problem.</span>
    <span class="tok-gu">a:</span> <span class="tok-nf">random</span> <span class="tok-m">10</span>
    <span class="tok-gu">b:</span> <span class="tok-nf">random</span> <span class="tok-m">10</span>
    <span class="tok-gu">answer:</span> <span class="tok-nv">a</span> <span class="tok-o">*</span> <span class="tok-nv">b</span>

    <span class="tok-c">; Get the user&#39;s response (converting it to the right datatype)</span>
    <span class="tok-gu">response:</span> <span class="tok-k">to-integer</span> <span class="tok-ne">ask</span> <span class="tok-gs">[</span> <span class="tok-nv">a</span> <span class="tok-s">&quot;x&quot;</span> <span class="tok-nv">b</span> <span class="tok-s">&quot;= &quot;</span> <span class="tok-gs">]</span>

    <span class="tok-c">; Evaluate the response.</span>
    <span class="tok-nb">either</span> <span class="tok-k">strict-equal?</span> <span class="tok-nv">answer</span> <span class="tok-nv">response</span> <span class="tok-gs">[</span>
        <span class="tok-gu">correct:</span> <span class="tok-nv">correct</span> <span class="tok-o">+</span> <span class="tok-m">1</span>
        <span class="tok-nb">print</span> <span class="tok-s">&quot;That&#39;s correct!&quot;</span>
    <span class="tok-gs">]</span> <span class="tok-gs">[</span>
        <span class="tok-nb">print</span> <span class="tok-gs">[</span> <span class="tok-s">&quot;Sorry, it&#39;s&quot;</span> <span class="tok-nv">answer</span> <span class="tok-gs">]</span>
    <span class="tok-gs">]</span>
<span class="tok-gs">]</span>

<span class="tok-c">; Display the final results.</span>
<span class="tok-nb">print</span> <span class="tok-gs">[</span> <span class="tok-s">&quot;Out of&quot;</span> <span class="tok-nv">questions</span> <span class="tok-s">&quot;questions, you answered&quot;</span> <span class="tok-nv">correct</span> <span class="tok-s">&quot;correctly&quot;</span> <span class="tok-gs">]</span></code></pre>
</div>
</div>
<div class="paragraph">
<p>Nothing fancy is going on here.
We just <code>loop</code> through the question and answer process a few times, keeping track of the user’s correct answers.
<code>random/seed now</code> is necessary to get something close to what we would consider random.
If we don’t provide it, then we get a specific sequence whenever we call <code>random</code>.
Try commenting out the <code>random/seed</code> line and run the program a few times.
You’ll see what I mean.</p>
</div>
<div class="paragraph">
<p>You’re right.
A plain old <code>loop</code> isn’t very interesting.
Let’s move on.</p>
</div>
</div>
<div class="sect2">
<h3 id="_looping_forever">Looping <code>forever</code></h3>
<div class="paragraph">
<p>I’m only telling you this because I can see that one or two of you really want to know.
What if you want to run a loop forever?
Well, you don’t want to.
Maybe you want to run a loop until some signal is received, or the user wants to quit, or something sensible like that.
You don’t want a loop to run forever.
But that doesn’t mean you <em>can’t</em> run a loop forever.
REBOL provides us with the <code>forever</code> word to let us do exactly that.</p>
</div>
<div class="literalblock">
<div class="content">
<pre>&gt;&gt; forever [ print "spam." ]
spam.
spam.
spam.
...</pre>
</div>
</div>
<div class="paragraph">
<p>And so on until you hit <span class="keyseq"><kbd>Ctrl</kbd>+<kbd>C</kbd></span>, or kill the process, or do something to make the program <em>stop saying "spam"</em>!</p>
</div>
<div class="paragraph">
<p>But please, don’t use <code>forever</code> without a mighty good reason.</p>
</div>
</div>
<div class="sect2">
<h3 id="_break_out_of_a_loop"><code>break</code> out of a loop</h3>
<div class="paragraph">
<p>Sometimes you’re right in the middle of a loop and you want to break out of it and get back to the rest of the program.
That’s easy enough.</p>
</div>
<div class="literalblock">
<div class="content">
<pre>&gt;&gt; i: 0
== 0
&gt;&gt; forever [
[    prin i
[    i: i + 1
[    if equal? i 5 [
[        print "Augh!"
[        break
[        ]
[    ]
01234Augh!
&gt;&gt;</pre>
</div>
</div>
<div class="paragraph">
<p>Oh, you noticed that <code>prin</code> in there?
That’s a different way of printing.
Each call to <code>prin</code> puts its output immediately after the output from the previous <code>prin</code>, rather than on a new line.
It’s nothing major, but it is a nice feature to take advantage of every once in a while.</p>
</div>
<div class="paragraph">
<p>Right.
So we’ve covered simple loops.
Now let’s start getting a little more interesting.</p>
</div>
</div>
</div>
</div>
<div class="sect1">
<h2 id="_monitored_loops">Monitored Loops</h2>
<div class="sectionbody">
<div class="paragraph">
<p>Plain old repetition isn’t actually all that common.
We usually want to do something a little different each time we step through the loop.
REBOL gives us a few words which help us in that situation.</p>
</div>
<div class="sect2">
<h3 id="_repeat"><code>repeat</code></h3>
<div class="paragraph">
<p><code>repeat</code> works almost exactly the same as <code>loop</code>.
The main difference is that it stores the number of trips you’ve taken through the loop in a variable that you can get to from inside the loop.
The variable has a value of <code>1</code> on the first trip through, <code>2</code> on the second trip through, and so on.</p>
</div>
<div class="literalblock">
<div class="content">
<pre>&gt;&gt; repeat count 9 [
[    print [ "3 x" count "is" 3 * count ]
[    ]
3 x 1 is 3
3 x 2 is 6
3 x 3 is 9
3 x 4 is 12
3 x 5 is 15
3 x 6 is 18
3 x 7 is 21
3 x 8 is 24
3 x 9 is 27</pre>
</div>
</div>
</div>
<div class="sect2">
<h3 id="_for"><code>for</code></h3>
<div class="paragraph">
<p>The next sort of repetition structure is <code>for</code>, which adds a starting point, stopping point, and step size to the <code>repeat</code> loop.
<code>for</code> is useful for producing very specific loops.
It might be a little wordy for simple loops which can be handled by the <code>repeat</code> word:</p>
</div>
<div class="literalblock">
<div class="content">
<pre>&gt;&gt; for num 1 9 1 [ print ["3 x" num "is" 3 * num] ]</pre>
</div>
</div>
<div class="paragraph">
<p>We have a loop variable, <code>num</code>, which starts at <code>1</code> and goes up to <code>9</code> <code>1</code> number at a time.
Of course, <code>repeat num 9</code> does exactly the same thing.
<code>for</code> tends to be more useful in loops for "real-world" code, though, where you need more control over what’s being looped.
You want some real world code?
Hmm.
Oh, I know.
Let’s answer the age-old question, "How much should I tip?
That way we can play a little bit with some <a href="/post/2004/12/rebol-datatypes">datatypes</a> while helping out our friends in the food service industry.
Hey, what do you expect from me?
I was a waiter for ten years, so this is the sort of stuff that pops into my head!</p>
</div>
<div class="literalblock">
<div class="content">
<pre>&gt;&gt; for bill $10 $20 $1 [
[    tip: bill * .15
[    print ["Bill:" bill "-- Tip:" tip]
[    ]
Bill: $10.00 -- Tip: $1.50
Bill: $11.00 -- Tip: $1.65
Bill: $12.00 -- Tip: $1.80
Bill: $13.00 -- Tip: $1.95
Bill: $14.00 -- Tip: $2.10
Bill: $15.00 -- Tip: $2.25
Bill: $16.00 -- Tip: $2.40
Bill: $17.00 -- Tip: $2.55
Bill: $18.00 -- Tip: $2.70
Bill: $19.00 -- Tip: $2.85
Bill: $20.00 -- Tip: $3.00</pre>
</div>
</div>
<div class="paragraph">
<p>We can’t do <em>that</em> with a <code>repeat</code> loop.
At least, I don’t think we can.
We set the starting bill at <code>$10</code>, and moved up to <code>$20</code> by <code>$1</code> at a time, showing the bill and corresponding average tip.
It’s still a very small thing.
The fact that it recognizes the values as money and treats it appropriately is a special thrill for me.
If you haven’t programmed before, then you might just assume that things are supposed to work like this.
You would be right.
Things <em>should</em> work like this: transparent, and the obvious stuff should do the obvious.
But in C, there would be all sorts of chaos and <code>printf</code> madness and general ugliness that would get you so angry that you might not even bother leaving a tip.</p>
</div>
<div class="paragraph">
<p>And that would be bad, my friends.
Very bad indeed.</p>
</div>
<div class="paragraph">
<p>As long as I’m looking at datatypes in <code>for</code> loops, let’s look at another example.
Starting from Saturday, January 3 2009, what is the calendar date of each following Saturday until March 7 2009?</p>
</div>
<div class="literalblock">
<div class="content">
<pre>&gt;&gt; for day 3-jan-2009 7-mar-2009 7 [ print day ]
3-Jan-2009
10-Jan-2009
17-Jan-2009
24-Jan-2009
31-Jan-2009
7-Feb-2009
14-Feb-2009
21-Feb-2009
28-Feb-2009
7-Mar-2009</pre>
</div>
</div>
<div class="paragraph">
<p>Start on January 3, step 7 days at a time until we reach March 7, and print the calendar date at each step.
Not bad, eh?
I know that these all occured on a Saturday, but you’ll have to wait until later for me to explain it.
You want a clue?
Oh, all right.
I used <code>day/weekday</code>, got <code>6</code>, and figured out that the sixth day of the week is Saturday.</p>
</div>
<div class="paragraph">
<p>Or maybe I looked at a calendar.
I’ll never tell.</p>
</div>
</div>
</div>
</div>
<div class="sect1">
<h2 id="_conditional_loops">Conditional Loops</h2>
<div class="sectionbody">
<div class="paragraph">
<p>Then there are the times when you aren’t sure exactly when you’ll need to stop.
You need to keep going until it’s time to stop, basically.
Now, you could use a <code>forever</code> loop and <code>break</code> whenever you need to stop.
But I don’t want you to do that.
Why am I so opposed to an approach like that?
It comes down to clarity.
Somebody will be reading your code a few weeks, months, or even years after you write it.
That person could be you.</p>
</div>
<div class="paragraph">
<p>Don’t laugh - I’m still haunted by a script that I wrote years ago when I was first learning Perl.
I thought I’d just be throwing that script away, but I still use it.
I still cringe every time I have to read it, too.
And yes, it had a couple of <code>forever</code>-style loops.
I want to save you from the embarassment of bad code whenever possible.</p>
</div>
<div class="paragraph">
<p>But I digress.
Let’s look at the conditional loops.
There are two main conditional loops, <code>until</code> and <code>while</code>.
The difference between the two from our perspective is when they test to see whether it’s time to quit the loop.</p>
</div>
<div class="sect2">
<h3 id="_keep_going_until_something_is_true">Keep going <code>until</code> something is true</h3>
<div class="paragraph">
<p>The <code>until</code> loop tests at the end of each step of the loop.
If the block returns true, then it’s time to quit.
How do you know if the block returns <code>true</code>?
Because the block returns the value of the last statement in the block.
This means that we could put a simple test as the last statement, using the guidelines from the chapter on {selection structures}.</p>
</div>
<div class="literalblock">
<div class="content">
<pre>&gt;&gt; until [
[    print "Spam"
[    response: ask "? "
[    equal? response "Bloody Vikings!"
[    ]
Spam
? Spam
Spam
? Bacon Eggs and Spam
Spam
? I don't like Spam!
Spam
? Bloody Vikings!
== true</pre>
</div>
</div>
<div class="paragraph">
<p>Because it doesn’t test until the end of the loop, <code>until</code> will step through the loop at least once.</p>
</div>
</div>
<div class="sect2">
<h3 id="_keep_going_while_something_is_true">Keep going <code>while</code> something is true</h3>
<div class="paragraph">
<p><code>while</code> takes a test block and a loop block.
There’s all sorts of clever things we can do in the test block, but for now we’ll just put simple tests in it.
If the test comes up false, then <code>while</code> doesn’t bother running through the loop.
If it’s true, then it runs through the loop and tests again.</p>
</div>
<div class="paragraph">
<p>Hrm, I need to think of a decent example of <code>while</code>.
For now, let’s just make a variation of what we might do with an <code>until</code> loop.</p>
</div>
<div class="literalblock">
<div class="content">
<pre>&gt;&gt; response: none
== none
&gt;&gt; while [ not-equal? response "Bloody Vikings!" ] [
[    print "Spam."
[    response: ask "? "
[    ]
Spam.
? flerg
Spam.
? flop
Spam.
? Bloody Vikings!
== "Bloody Vikings!"</pre>
</div>
</div>
<div class="paragraph">
<p><code>while</code> will not run at all if the condition isn’t true at the start of the loop, because it tests the condition before beginning each step.</p>
</div>
</div>
</div>
</div>
<div class="sect1">
<h2 id="_stepping_through_a_list">Stepping Through a List</h2>
<div class="sectionbody">
<div class="paragraph">
<p>The last form of repetition is iterating through a list.
A copy of each item in the list is passed to a temporary variable that you can play with in the loop block.
I will only look briefly at this form of repetition in this chapter, because list manipulation and iteration is a big topic in its own right.
Nevertheless, many of you will want to do <em>something</em> with lists before I get around to writing that next chapter.</p>
</div>
<div class="sect2">
<h3 id="_foreach"><code>foreach</code></h3>
<div class="paragraph">
<p>The basic list iteration function is <code>foreach</code>.
It takes a name, a list variable, and a block.
<code>foreach</code> repeats the loop once for each item in the list.
The name is set to the value of the current item in the list.
It is easier to demonstrate a <code>foreach</code> loop than it is to describe one.
Here’s a quick example.</p>
</div>
<div class="literalblock">
<div class="content">
<pre>&gt;&gt; colors: to-list [ "red" "green" "blue" ]
== make list! ["red" "green" "blue"]
&gt;&gt; foreach color colors [ print color ]
red
green
blue</pre>
</div>
</div>
<div class="paragraph">
<p>I would like to close this chapter with something a little meatier than that example, though.
Let’s write a script that takes a list of dates and tells us how far from today each of those dates are.</p>
</div>
<div class="listingblock">
<div class="content">
<pre class="pygments highlight"><code data-lang="rebol"><span></span><span class="tok-gs">REBOL [</span>
    <span class="tok-gu">file:</span> <span class="tok-nd">%days.r</span>
    <span class="tok-gu">purpose:</span> <span class="tok-s">{ Simple demonstration of iterating through a list }</span>
<span class="tok-gs">]</span>

<span class="tok-c">; Feel free to create your own list of days</span>
<span class="tok-gu">days:</span> <span class="tok-k">to-list</span> <span class="tok-gs">[</span>
    <span class="tok-sx">23-Jan-2009</span> <span class="tok-sx">24-Feb-2009</span> <span class="tok-sx">13-Mar-2009</span> <span class="tok-sx">30-Apr-2009</span> <span class="tok-sx">31-Oct-2009</span> <span class="tok-sx">5-Jan-2010</span>
<span class="tok-gs">]</span>

<span class="tok-nb">foreach</span> <span class="tok-nv">day</span> <span class="tok-nv">days</span> <span class="tok-gs">[</span>
    <span class="tok-c">; Determine how many days we are from &#39;day&#39;</span>
    <span class="tok-gu">day-span:</span> <span class="tok-nv">day</span> <span class="tok-o">-</span> <span class="tok-nb">now</span>

    <span class="tok-c">; &#39;day_span&#39; will be negative for days in the past, and we need a</span>
    <span class="tok-c">; positive number for our phrase below</span>
    <span class="tok-gu">absolute-span:</span> <span class="tok-nf">abs</span> <span class="tok-nv">day-span</span>

    <span class="tok-c">; Make sure that our phrase uses the correct form of the word &#39;day&#39;</span>
    <span class="tok-gu">day-string:</span> <span class="tok-nb">either</span> <span class="tok-nv">absolute-span</span> <span class="tok-o">&gt;</span> <span class="tok-m">1</span> <span class="tok-gs">[</span> <span class="tok-s">&quot;days&quot;</span> <span class="tok-gs">]</span> <span class="tok-gs">[</span> <span class="tok-s">&quot;day&quot;</span> <span class="tok-gs">]</span>

    <span class="tok-nb">either</span> <span class="tok-nv">day-span</span> <span class="tok-o">&gt;</span> <span class="tok-m">0</span> <span class="tok-gs">[</span>
        <span class="tok-c">; &#39;day&#39; is in the future.</span>
        <span class="tok-nb">print</span> <span class="tok-gs">[</span> <span class="tok-nv">day</span> <span class="tok-s">&quot;is in&quot;</span> <span class="tok-nv">day-span</span> <span class="tok-nv">day-string</span> <span class="tok-gs">]</span>
    <span class="tok-gs">]</span> <span class="tok-gs">[</span>
        <span class="tok-nb">either</span> <span class="tok-nv">day-span</span> <span class="tok-o">&lt;</span> <span class="tok-m">0</span> <span class="tok-gs">[</span>
            <span class="tok-c">; &#39;day&#39; is in the past.</span>
            <span class="tok-nb">print</span> <span class="tok-gs">[</span> <span class="tok-nv">day</span> <span class="tok-s">&quot;was&quot;</span> <span class="tok-nv">absolute-span</span> <span class="tok-nv">day-string</span> <span class="tok-s">&quot;ago&quot;</span> <span class="tok-gs">]</span>
        <span class="tok-gs">]</span> <span class="tok-gs">[</span>
            <span class="tok-nb">print</span> <span class="tok-gs">[</span> <span class="tok-nv">day</span> <span class="tok-s">&quot;is today!&quot;</span> <span class="tok-gs">]</span>
        <span class="tok-gs">]</span>
    <span class="tok-gs">]</span>
<span class="tok-gs">]</span></code></pre>
</div>
</div>
<div class="paragraph">
<p>Now that we’ve written the code, let’s run the script:</p>
</div>
<div class="literalblock">
<div class="content">
<pre>23-Jan-2009 was 32 days ago
24-Feb-2009 is today!
13-Mar-2009 is in 17 days
30-Apr-2009 is in 65 days
31-Oct-2009 is in 249 days
5-Jan-2010 is in 315 days</pre>
</div>
</div>
<div class="paragraph">
<p>Naturally, your results may vary.
In fact, they will almost definitely vary unless you read this article the day I updated it or your clock is set wrong.
I encourage you to play with this script and come up with your own variations.
How about a script that asks the user for a date and tells how far that day is from today?
You’ll probably need to use <code>to-date</code> on the user input.</p>
</div>
</div>
</div>
</div>
<div class="sect1">
<h2 id="_conclusion_and_congratulations">Conclusion and Congratulations</h2>
<div class="sectionbody">
<div class="paragraph">
<p>Completing this chapter means you have hit a significant milestone in programming by learning all of the basic elements of something called "Structured Programming".
It is now possible for you to build non-trivial, "real-world" programs using REBOL.
I will try to keep this in mind when putting together future chapters in this tutorial.</p>
</div>
</div>
</div>