---
title: "Basic DIY Sea Salt Spray"
caption: "Sea salt, argan oil, and a spray bottle. You need water too."
announcement: "In which I write a hair spray recipe and *then* share the story"
announcements:
  mastodon: https://hackers.town/@randomgeek/103004338629886575
  twitter: https://twitter.com/brianwisti/status/1186512051168071680
year: "2019"
date: 2019-10-21
tags:
- diy
- recipe
- grooming
categories:
- Marginalia
---

*tl;dr:* Heat a cup of water. Mix in 2 teaspoons argan oil, 1 tablespoon sea salt, and a few drops
of something pretty. Let it cool. Shake before each use.

<!--more-->

== The recipe

Get ingredients at your favorite local market or evil online megacorporation!

.Ingredients
* Sea salt footnote:[If Dead Sea Celtic Himalayan Pink Salt makes you happy, go for it!]
* Argan oil footnote:[Or avocado oil if you feel fancy, or olive oil if that's what you got, but use less if so -- olive oil is thicker]
* Spray bottle footnote:[Preferably made of glass, since it's going to hold hot water]
* Funnel
* Maybe a whisk
* Kettle or other means of making cold water hot

That's pretty much all you _need_. You're free to add more!

.Extras
* tea tree, sandalwood, or some other essential oil with a smell that pleases you
* hair gel or coconut oil -- for additional hold
* epsom salt -- for magnesium, I guess?

.Instructions
. Heat some water in the kettle. If it boils, let it cool a moment. You don't want your
  first hairspray story to involve burn treatment.
. Measure out one cup (roughly 250 ml) of hot water
. Whisk in 2 teaspoons of oil. You can vary this a bit more or less depending on how dry your hair gets.
. Whisk in a tablespoon of sea salt. A little more gives more hold, but careful to avoid crusty hair!
. If you want your hair to smell nice, whisk in a few drops of essential oil.footnote:[I tried
beard oil once and it added nothing. Too diluted already maybe. Use a proper essential oil -- or invent your
own mix!]
. Pour your mix into the spray bottle with a funnel, unless you have very steady hands!
. Let it cool to room temperature or at least until there's no risk of burns.
. Shake vigorously before each use!

One batch lasts me over a month of daily use, but I intentionally go for a lighter hold. Out of
my face and roughly pointed in the right direction is all I care about.

{{< show-figure
  image="me.jpg"
  description="Still roughly pointed in the right direction halfway through the day" >}}

== The story

Now that the recipe is out of the way -- I thought cookbooks were bad about forcing you to read a long story
before giving you their instructions. Cookbooks are nothing. Those self-care blogs are _awful_. An evening
searching and I couldn't find the source for the basic recipe I've been using over the last year or so because
I couldn't get through all the _stories_.

:three_virtues: http://threevirtues.com/

I had this big story in mind about how I was watching a beard care video one night and they said "use sea
salt spray! It's good on your hair!" and I said "okay!" and they said "use _our_ sea salt spray!" and I said "at that
price? H*ck no!" I was even going to work in some link:/tags/perl[Perl] references. Talk about how making your
own hair spray is another application of {three_virtues}[The Three Virtues].

But I got bored just writing the outline for that particular story. Now it's a year later, and I'm
just writing down a recipe somewhere permanent to avoid losing it again.

Look around for ideas from other recipes, but take what you read with a grain of sea salt. We're here for mad
science and saving money, not Clean Living or Purity Of Essence.

{{< youtube "iyj_D2ivwS4" >}}

Anyways.

This recipe is what I came up with last night after giving up on my search. You can find
many recipes with varying ingredients and proportions. Experiment. Figure out what works for you.

Then write it down somewhere so you aren't making something up again when you run out.

== Epilogue

:gimme_some_oven: https://www.gimmesomeoven.com/diy/diy-sea-salt-texturizing-hair-spray/

I found the recipe I started with! {gimme_some_oven}[Gimme Some Oven] has the information you need. Not much
different than what you'll find here, though with less Dr. Strangelove.

